DROP TABLE GAB_3908_UF_NAMES;
CREATE TABLE GAB_3908_UF_NAMES(
ID INTEGER,
FORM_ID INTEGER,
NAME VARCHAR(50),
REQUIRED BIT
);

CREATE UNIQUE NOT MODIFIABLE INDEX GAB_3908_UF_NAMES00 USING 0 ON GAB_3908_UF_NAMES(ID, FORM_ID);