DROP TABLE GAB_3908_UF_VALUES;
CREATE TABLE GAB_3908_UF_VALUES(
ID INTEGER,
FORM_ID INTEGER,
UF_ID INTEGER,
VALUE VARCHAR(100)
);

CREATE UNIQUE NOT MODIFIABLE INDEX GAB_3908_UF_VALUES00 USING 0 ON GAB_3908_UF_VALUES(ID, FORM_ID, UF_ID);